### PR TITLE
Fix app crash on video frame read

### LINKED ISSUE #10: App crashing on some video recording settings
## Expected Behavior
The app should work with all video-recording settings in the first selector Activity.

## Actual Behavior
App crashes on some video-recording setting after pressing `START ANALYSIS` button.

## Steps to Reproduce the Problem

1. Install app on specified master version.
1. Try the end-to-end experiement using Server with all settings shown on selector activity.
1. The app will crash on some of the setting.

## Specifications

- Version: App based on commit 1a449d3be6ef1ea5d051b8d93e711cc491d14d25

### PR DESCRIPTION
**Pull request by aquatiko**
Previously app was trying to read all video frames in a single request
to `mediaMetadataRetriever`, now video file is loaded in chunks.

**Fixes:** #10 

Looks like some limitation on `mediaMetadataRetriever` API being unable to read all frames at once.
**Note:** A disadvantage obeserved while reading in chunks was longer load time opposed to a single load requests (which crashes on large requests).

### CODE REVIEW

File: Camera2SlowMotion/app/src/main/java/com/example/android/camera2/slowmo/MainActivity.java [hunk 1]
```diff
@@ -113,8 +113,12 @@ private void analyze() {
     totalFrames =
         Integer.valueOf(mediaMetadataRetriever.extractMetadata(METADATA_KEY_VIDEO_FRAME_COUNT));
     // TODO: Add on demand frame read opposed to read all frames.
-    frameList = mediaMetadataRetriever.getFramesAtIndex(0, Math.max(0, totalFrames - SAFE_FRAMES));
-
+    for (int i = 0; i < totalFrames; i += FRAME_CHUNK_READ_SIZE) {
+      if (i + FRAME_CHUNK_READ_SIZE - 1 < totalFrames)
+        frameList.addAll(mediaMetadataRetriever.getFramesAtIndex(i, FRAME_CHUNK_READ_SIZE));
+      else
+        frameList.addAll(mediaMetadataRetriever.getFramesAtIndex(i, totalFrames-i));
```
Comment (mwarton) [inline Camera2SlowMotion/app/src/main/java/com/example/android/camera2/slowmo/MainActivity.java]: frameList.addAll(mediaMetadataRetriever.getFramesAtIndex(i, Math.min(totalFrames - i, FRAME_CHUNK_READ_SIZE))

File: Camera2SlowMotion/app/src/main/java/com/example/android/camera2/slowmo/MainActivity.java [hunk 2]
```diff
@@ -113,8 +113,12 @@ private void analyze() {
     totalFrames =
         Integer.valueOf(mediaMetadataRetriever.extractMetadata(METADATA_KEY_VIDEO_FRAME_COUNT));
     // TODO: Add on demand frame read opposed to read all frames.
-    frameList = mediaMetadataRetriever.getFramesAtIndex(0, Math.max(0, totalFrames - SAFE_FRAMES));
```
Comment (mwarton) [inline Camera2SlowMotion/app/src/main/java/com/example/android/camera2/slowmo/MainActivity.java:116]: Any details on why this crashed?  did you get an excpetion message?

I would of assumed it was because it was too large for memory, but in that case the new code should crash too, so I'm not sure what the problem is.

**Review by mwarton — COMMENTED** [review]
Looks ok if it works, but a better design would be to only read chunks of frames as we need them for analysis, and then discard them after the analysis to reduce memory usage.

File: Camera2SlowMotion/app/src/main/java/com/example/android/camera2/slowmo/MainActivity.java (hunk 1 above)
Comment (aquatiko) [reply Camera2SlowMotion/app/src/main/java/com/example/android/camera2/slowmo/MainActivity.java]: That makes sense. Thanks!
> Looks ok if it works, but a better design would be to only read chunks of frames as we need them for analysis, and then discard them after the analysis to reduce memory usage.

I added a TODO to read frames on demand, I planned to do that when optimizing the linear algorithm for finding `serverSequence` among the OCR texts.

File: Camera2SlowMotion/app/src/main/java/com/example/android/camera2/slowmo/MainActivity.java (hunk 2 above)
Comment (aquatiko) [reply Camera2SlowMotion/app/src/main/java/com/example/android/camera2/slowmo/MainActivity.java:116]: @mwarton Added a log to catch the exception.
Added details to the issue #10 discussion.

File: Camera2SlowMotion/app/src/main/java/com/example/android/camera2/slowmo/MainActivity.java [hunk 3]
```diff
@@ -113,8 +114,15 @@ private void analyze() {
...
+    for (int i = 0; i < totalFrames; i += FRAME_CHUNK_READ_SIZE) {
+      try{
+        frameList.addAll(mediaMetadataRetriever.getFramesAtIndex(
+            i, Math.min(totalFrames - i, FRAME_CHUNK_READ_SIZE)));
+      }catch (IllegalStateException e){
+        Log.d(ContentValues.TAG, "Video chunk read unsuccessful with: "+ e.getMessage());
```
Comment (mwarton) [inline Camera2SlowMotion/app/src/main/java/com/example/android/camera2/slowmo/MainActivity.java:122]: Shouldn't we abort the analysis?  Incomplete or completely missing frames will mess up the results won't they?

Comment (aquatiko) [reply Camera2SlowMotion/app/src/main/java/com/example/android/camera2/slowmo/MainActivity.java:122]: @mwarton fixed. I added a command to kill the activity and fall back to previous activity to start the capture again.

**Review by mwarton — APPROVED** [review]

File: Camera2SlowMotion/app/src/main/java/com/example/android/camera2/slowmo/MainActivity.java [hunk 4]
```diff
@@ -113,8 +114,16 @@ private void analyze() {
     totalFrames =
         Integer.valueOf(mediaMetadataRetriever.extractMetadata(METADATA_KEY_VIDEO_FRAME_COUNT));
     // TODO: Add on demand frame read opposed to read all frames.
-    frameList = mediaMetadataRetriever.getFramesAtIndex(0, Math.max(0, totalFrames - SAFE_FRAMES));
+    for (int i = 0; i < totalFrames; i += FRAME_CHUNK_READ_SIZE) {
+      try{
+        frameList.addAll(mediaMetadataRetriever.getFramesAtIndex(
+            i, Math.min(totalFrames - i, FRAME_CHUNK_READ_SIZE)));
+      }catch (IllegalStateException e){
```
Comment (patrickmeiring) [inline Camera2SlowMotion/app/src/main/java/com/example/android/camera2/slowmo/MainActivity.java:121]: Please run the formatter to fix up the whitespace before submitting.
https://google.github.io/styleguide/javaguide.html#s4-formatting
try {
...
} catch (IllegalStateException e) {
 ...
}

**Review by patrickmeiring — COMMENTED** [review]
LGTM % nits

File: Camera2SlowMotion/app/src/main/java/com/example/android/camera2/slowmo/MainActivity.java (hunk 4 above)
Comment (patrickmeiring) [reply Camera2SlowMotion/app/src/main/java/com/example/android/camera2/slowmo/MainActivity.java:121]: As discussed, I'll merge now and we'll fix this in a follow up.
